name: .NET Core CI

on:
  [workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build ./template/backend/Ambev.DeveloperEvaluation.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./template/backend/tests/Ambev.DeveloperEvaluation.Unit/Ambev.DeveloperEvaluation.Unit.csproj --no-build --configuration Release --verbosity normal
